//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModusMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant()
        {
            this.CareerApplicants = new HashSet<CareerApplicant>();
        }
    
        public int ApplicantID { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantSurname { get; set; }
        public string ApplicantIdentity { get; set; }
        public string ApplicantCell { get; set; }
        public string ApplicantEmail { get; set; }
        public string ApplicantCV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareerApplicant> CareerApplicants { get; set; }
    }
}
