//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModusMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerApplicant
    {
        public int ApplicationNumber { get; set; }
        public Nullable<int> CareerID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public string ApplicationPosition { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Career Career { get; set; }
    }
}
